version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: education_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - education_network
  

  migrations:
    image: gomicro/goose:latest
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backend/db/migrations:/migrations
    command: ["goose", "-dir", "/migrations", "up"]
    restart: on-failure
    networks:
      - education_network
  
  # ml-service:
  #   build:
  #     context: ./ml-service
  #     dockerfile: Dockerfile
  #   container_name: education_ml
  #   restart: unless-stopped
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_NAME: education_platform
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ./ml-service/app:/app/app
  #   networks:
  #     - education_network

volumes:
  postgres_data:
    driver: local

networks:
  education_network:
    driver: bridge